### ISSUE TITLE
모듈설치가 안됩니다.

### ISSUE THREAD

**Issue by byoungseoklee** [Kimjio/umamusume-localify-android#1]
copying zip to temp directory
 Magisk 25에서 위에 문구로 설치가 안됩니다.

**Comment by Kimjio** [comment]
이쪽 문제는 아닌 것 같은데, Magisk 앱 업데이트나 기기 재시작을 해도 동일한가요?
현재 release에 올려놓은 파일로 했는데 정상으로 설치되네요.
![Screenshot_20220624-235736_Magisk](https://user-images.githubusercontent.com/10695980/175562185-74580257-a0fc-4c63-9d9f-7b3048a8aec8.png)

**Comment by byoungseoklee** [comment]
답변 감사합니다. 릴리즈에 올려두신 파일로 하니깐 정상 설치 됐습니다. 제가 깃허브는 처음사용해서 인지를 잘못했는데
엊그제 잘설치해서 잘 사용하고 있습니다. 정말 감사합니다!
태블릿 s8+ 에서 정상 작동 및 안티 , 프레임 잘작동 되는거 확인 했었습니다.
정말 소중한 자료 감사합니다!
 
-----Original Message-----

**Comment by Kimjio** [comment]
이상 없으면 해당 이슈는 닫겠습니다.
