### ISSUE TITLE
Localization of config-json

### ISSUE THREAD

**Issue by Lyzzsha** [Kimjio/umamusume-localify-android#22]
Hello all.
Dont understand this:

Put the config.json file in /sdcard/android/data/jp.co.cygames.umamusume/ and the translation file referenced in dicts.

But, WHERE is config.json?
And where is the "dicts" translation place? And what translation file should one move?

In the releases - assets, its impossible to find this.

Can you help me or clarify the Readme?

Thanks!! :3

**Comment by Kimjio** [comment]
You'll need to create the config.json yourself.

In `dicts`, you can put any path that is accessible to the app.
This means you can put the json file anywhere in the path `/sdcard/android/data/jp.co.cygames.umamusume/`.

You can put the JSON file translated into your language.

You can see a sample config.json [here](https://github.com/Kimjio/umamusume-localify-android/blob/main/resources/config.json).

I recommend using the Settings app, which allows you to set all the options you can put in your config.json.
You can get the Settings app from the [releases page](https://github.com/Kimjio/umamusume-localify-android/releases) or the [Play Store](https://play.google.com/store/apps/details?id=com.kimjio.umamusumelocalify.settings).

README file: out of date. I will update it when I have time.
