### ISSUE TITLE
만들어주신 LD 버전 패키지에서 2.5.0부터 100% 크래시납니다 ㅠㅠ

### ISSUE THREAD

**Issue by fespixel** [Kimjio/umamusume-localify-android#9]
일단 2.4.0으로 되돌렸습니다 실행이 안돼용

**Comment by Kimjio** [comment]
윈도우판 우선 본다고 이쪽을 거의 못 건들고 있었는데
카카오가 일섭, 대만섭처럼 알림 관련 코드 안 건들고
푸시 이미지 리소스만 3배 늘리는 방법을 사용해서 나는 오류네요...

해당 문제는 수정 완료해서 업데이트 해도 문제 없습니다.
